# Data 

custom_scene_brightness: "bright" #[dark, normal, bright]
grayscale: True # False
input_edge: True # False
augment: True # False
with_arms: False
val_split_ratio: 0.01
n_classes: 3
in_channels: 3

# Training

batch_size: 32
n_epochs: 10
max_epoch_iterations: 500
optimizer: 
  name: "AdamW"
  lr: 0.001
  params:
    weight_decay: 0.0001
    eps: 1.e-08
scheduler: 
  use: False
  name: "ReduceLROnPlateau"
  params:
    factor: 0.1
    patience: 3
    min_lr: 0.00001
    mode: "min"
    verbose: True
criterion:
  use_custom: False
  name: "CrossEntropyLoss"
  params: null
device: 0
distributed: False

# Validation

validate_interval: 1
validate_on: loss

# Logging and checkpointing

log_dir: "./logs"
log_iterations_interval: 100
ckpt_dir: "./ckpts"
ckpt_interval: 1

# Resume training

resume_training:
  consolidated_ckpt: null
  n_epochs: 10
  start_epoch: null
