# Data 

custom_scene_brightness: "normal" #[dark, normal, bright]
grayscale: False
input_edge: False
with_arms: False
val_split_ratio: 0.05
n_classes: 3
in_channels: 1

# Training

batch_size: 32
n_epochs: 10
eval_interval: 1
optimizer: 
  name: "SGD"
  lr: 0.001
  params:
    momentum: 0.9
    weight_decay: 0.001
scheduler: 
  use: False
  name: "ReduceLROnPlateau"
  params:
    factor: 0.1
    patience: 3
    min_lr: 0.00001
    mode: "min"
    verbose: True
criterion:
  use_custom: True
  name: "CrossEntropyLoss"
  params: null
device: 0
distributed: False

# Validation

validate_interval: 1
validate_on: loss

# Logging and checkpointing

log_dir: "./logs"
log_iterations_interval: 1000
ckpt_dir: "./ckpts"
ckpt_interval: 1

# Resume training

resume_training:
  consolidated_ckpt: null
  n_epochs: 10
  start_epoch: null
