# Data config

custom_scene_brightness: "normal" #[dark, normal, bright]
input_edge: False
with_arms: False
val_split_ratio: 0.1

# Training config

device: 0
batch_size: 16
max_iters: 10
display_interval: 10
save_interval: 10
log_interval: 10
logdir: "./runs"
num_classes : 3
weight_decay: 0.001
lr: 0.0001
lr_policy: 'step'
policy_parameter_seg:
  gamma: 0.5
  step_size: 20000
optimizer: "SGD"
momentum: 0.9