# Data config

custom_scene_brightness: "normal" #[dark, normal, bright]
input_edge: False
with_arms: False
val_split_ratio: 0.05
n_classes: 3
in_channels: 1

# Training config

batch_size: 16
epochs: 10
eval_interval: 1
save_interval: 1
save_dir: "./model_weights"
log: True
log_dir: "./experiments"
weight_decay: 0.001
lr: 0.001
lr_scheduler: "StepLR"
lr_policy:
  gamma: 0.5
  step_size: 20000
optimizer: "SGD"
momentum: 0.9
